FROM ubuntu:latest
RUN apt-get update && apt-get install -y gcc default-libmysqlclient-dev
WORKDIR /app
COPY server.c .
RUN gcc server.c -o server_exe -lmysqlclient -lpthread
CMD ["./server_exe"]